export const orgChartData = [
  {
    type: "person",
    expanded: true,
    data: {
      department: "Chief of Hospital",
      deployment: "Director's Office",
      plantillaItem: "",
      prefix: "",
      firstName: "Dave Anthony",
      middleName: "",
      middleInitial: "A",
      lastName: "Vergara",
      suffix: "",
      postTitle: "MD",
      role: "Medical Center Chief I",
      gender: "",
      borderColor: "yellow",
      employmentType: "Plantilla",
      aligned: true,
      employeeId: "RMBGH-00001",
      image: `https://cdn3.iconfinder.com/data/icons/avatars-flat/33/man_5-1024.png`,
    },
    children: [
      // Medical Director
      {
        type: "person",
        expanded: true,
        data: {
          department: "Medical Director",
          deployment: "Director's Office",
          plantillaItem: "",
          prefix: "",
          firstName: "Mario Victor",
          middleName: "M",
          middleInitial: "M",
          lastName: "Villardo",
          suffix: "",
          postTitle: "MD",
          role: "Medical Director",
          borderColor: "blue",
          employmentType: "Plantilla",
          aligned: true,
          employeeId: "RMBGH-0133566",
          image: `https://cdn3.iconfinder.com/data/icons/avatars-flat/33/man_5-1024.png`,
        },
        children: [
          // Medical Services
          {
            type: "person",
            expanded: true,
            data: {
              department: "Medical Services",
              deployment: "Assistant Director Office",
              plantillaItem: "",
              prefix: "",
              firstName: "Clodoaido",
              middleName: "M",
              middleInitial: "M",
              lastName: "Caringal",
              suffix: "",
              postTitle: "MD",
              role: "Assistant Director for Medical Services",
              borderColor: "pink",
              employmentType: "Plantilla",
              aligned: true,
              employeeId: "RMBGH-00003",
              image: `https://cdn3.iconfinder.com/data/icons/avatars-flat/33/man_5-1024.png`,
            },
            children: [
              {
                type: "person",
                expanded: true,
                data: {
                  department: "Outpatient Department",
                  deployment: "Medical Services",
                  plantillaItem: "",
                  prefix: "",
                  firstName: "Sabina",
                  middleName: "",
                  middleInitial: "L",
                  lastName: "Mendoza",
                  suffix: "",
                  postTitle: "MD",
                  role: "Head, Outpatient Department",
                  borderColor: "brown",
                  employmentType: "Plantilla",
                  aligned: true,
                  employeeId: "RMBGH-MS-001",
                  image: `https://cdn2.iconfinder.com/data/icons/business-finance-ii-flat/2048/Business_Woman-4096.png`,
                },
                children: [
                  {
                    type: "person",
                    expanded: true,
                    data: {
                      department: "Internal Medicine",
                      deployment: "Outpatient Department",
                      plantillaItem: "",
                      prefix: "",
                      firstName: "Cristela",
                      middleName: "",
                      middleInitial: "V",
                      lastName: "Veñegas",
                      suffix: "",
                      postTitle: "MD",
                      role: "Officer-in-Charge, Internal Medicine",
                      borderColor: "brown",
                      employmentType: "Plantilla",
                      aligned: true,
                      employeeId: "RMBGH-MS-002",
                      image: `https://cdn2.iconfinder.com/data/icons/business-finance-ii-flat/2048/Business_Woman-4096.png`,
                    },
                    children: [
                      {
                        type: "person",
                        expanded: true,
                        data: {
                          department: "Family Medicine",
                          deployment: "Internal Medicine",
                          plantillaItem: "",
                          prefix: "",
                          firstName: "Robert ",
                          middleName: "",
                          middleInitial: "B",
                          lastName: "Belleza",
                          suffix: "",
                          postTitle: "MD",
                          role: "Head, Family Medicine",
                          borderColor: "brown",
                          employmentType: "Plantilla",
                          aligned: true,
                          employeeId: "RMBGH-MS-003",
                          image: `https://cdn3.iconfinder.com/data/icons/avatars-flat/33/man_5-1024.png`,
                        },
                        children: [
                          {
                            type: "person",
                            expanded: true,
                            data: {
                              debuggerepartment: "Pediatrics",
                              deployment: "Family Medicine",
                              plantillaItem: "",
                              prefix: "",
                              firstName: "Joanne Raquel ",
                              middleName: "",
                              middleInitial: "R",
                              lastName: "Teodoro",
                              suffix: "",
                              postTitle: "MD",
                              role: "Head, Pediatrics",
                              borderColor: "brown",
                              employmentType: "Plantilla",
                              aligned: true,
                              employeeId: "RMBGH-MS-004",
                              image: `https://cdn2.iconfinder.com/data/icons/business-finance-ii-flat/2048/Business_Woman-4096.png`,
                            },
                            children: [
                              {
                                type: "person",
                                expanded: true,
                                data: {
                                  department: "Hemodialysis",
                                  deployment: "Pediatrics",
                                  plantillaItem: "",
                                  prefix: "",
                                  firstName: "Aina",
                                  middleName: "",
                                  middleInitial: "",
                                  lastName: "Duque",
                                  suffix: "",
                                  postTitle: "MD",
                                  role: "Head, Hemodialysis",
                                  borderColor: "brown",
                                  employmentType: "Plantilla",
                                  aligned: true,
                                  employeeId: "RMBGH-MS-005",
                                  image: `https://cdn2.iconfinder.com/data/icons/avatars-flat/33/woman_5-1024.png`,
                                },
                                children: [
                                  {
                                    type: "person",
                                    expanded: true,
                                    data: {
                                      department: "NICU",
                                      deployment: "Hemodialysis",
                                      plantillaItem: "",
                                      prefix: "",
                                      firstName: "Adelusa ",
                                      middleName: "",
                                      middleInitial: "",
                                      lastName: "De Guzman-Besin",
                                      suffix: "",
                                      postTitle: "MD",
                                      role: "NICU",
                                      borderColor: "brown",
                                      employmentType: "Plantilla",
                                      aligned: true,
                                      employeeId: "RMBGH-MS-006",
                                      image: `https://cdn2.iconfinder.com/data/icons/avatars-flat/33/woman_5-1024.png`,
                                    },
                                    children: [
                                      {
                                        type: "person",
                                        expanded: true,
                                        data: {
                                          department: "PICU",
                                          deployment: "NICU",
                                          plantillaItem: "",
                                          prefix: "",
                                          firstName: "Samantha",
                                          middleName: "",
                                          middleInitial: "",
                                          lastName: "Imperial",
                                          suffix: "",
                                          postTitle: "MD",
                                          role: "PICU",
                                          borderColor: "brown",
                                          employmentType: "Plantilla",
                                          aligned: true,
                                          employeeId: "RMBGH-MS-007",
                                          image: `https://cdn2.iconfinder.com/data/icons/avatars-flat/33/woman_5-1024.png`,
                                        },
                                        children: [
                                          {
                                            type: "person",
                                            expanded: true,
                                            data: {
                                              department: "IMCU / MICU",
                                              deployment: "PICU",
                                              plantillaItem: "",
                                              prefix: "",
                                              firstName: "Mario Victor",
                                              middleName: "M",
                                              middleInitial: "M",
                                              lastName: "Villardo",
                                              suffix: "",
                                              postTitle: "MD",
                                              role: "Head, IMCU & MICU",
                                              borderColor: "brown",
                                              employmentType: "Plantilla",
                                              aligned: true,
                                              employeeId: "RMBGH-MS-008",
                                              image: `https://cdn3.iconfinder.com/data/icons/avatars-flat/33/man_5-1024.png`,
                                            },
                                            children: [],
                                          },
                                        ],
                                      },
                                    ],
                                  },
                                ],
                              },
                            ],
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
            ],
          },

          // Surgical Services - Doc Rashida
          {
            type: "person",
            expanded: true,
            data: {
              department: "Surgical Services",
              deployment: "Assistant Director Office",
              plantillaItem: "",
              prefix: "",
              firstName: "Rashida Cawiya ",
              middleName: "Guiling",
              middleInitial: "C",
              lastName: "Decena",
              suffix: "",
              postTitle: "MD",
              role: "Assistant Director",
              borderColor: "pink",
              employmentType: "Plantilla",
              aligned: true,
              employeeId: "RMBGH-00004",
              image: `https://cdn2.iconfinder.com/data/icons/business-finance-ii-flat/2048/Business_Woman-4096.png`,
            },
            children: [
              {
                type: "person",
                expanded: true,
                data: {
                  department: "Surgery",
                  deployment: "Surgical Services",
                  plantillaItem: "",
                  prefix: "",
                  firstName: "Rashida Cawiya ",
                  middleName: "Guiling",
                  middleInitial: "C",
                  lastName: "Decena",
                  suffix: "",
                  postTitle: "MD",
                  role: "Head",
                  borderColor: "brown",
                  employmentType: "Plantilla",
                  aligned: true,
                  employeeId: "RMBGH-RG-001",
                  image: `https://cdn2.iconfinder.com/data/icons/business-finance-ii-flat/2048/Business_Woman-4096.png`,
                },
                children: [
                  {
                    type: "person",
                    expanded: true,
                    data: {
                      department: "Obstetrics & Gynecology",
                      deployment: "Surgery",
                      plantillaItem: "",
                      prefix: "",
                      firstName: "Anna Liza ",
                      middleName: "",
                      middleInitial: "C",
                      lastName: "Salita",
                      suffix: "",
                      postTitle: "MD",
                      role: "Head",
                      borderColor: "brown",
                      employmentType: "Plantilla",
                      aligned: true,
                      employeeId: "RMBGH-RG-002",
                      image: `https://cdn2.iconfinder.com/data/icons/business-finance-ii-flat/2048/Business_Woman-4096.png`,
                    },
                    children: [
                      {
                        type: "person",
                        expanded: true,
                        data: {
                          department: "Anesthesiology",
                          deployment: "Obstetrics & Gynecology",
                          plantillaItem: "",
                          prefix: "",
                          firstName: "Malaika",
                          middleName: "",
                          middleInitial: "L",
                          lastName: "Salido-Ecalnir",
                          suffix: "",
                          postTitle: "MD",
                          role: "Head",
                          borderColor: "brown",
                          employmentType: "Plantilla",
                          aligned: true,
                          employeeId: "RMBGH-RG-003",
                          image: `https://cdn2.iconfinder.com/data/icons/business-finance-ii-flat/2048/Business_Woman-4096.png`,
                        },
                        children: [
                          {
                            type: "person",
                            expanded: true,
                            data: {
                              department: "Emergency",
                              deployment: "Anesthesiology",
                              plantillaItem: "",
                              prefix: "",
                              firstName: "Vacant",
                              middleName: "",
                              middleInitial: "",
                              lastName: "",
                              suffix: "",
                              postTitle: "",
                              role: "Officer-in-Charge",
                              borderColor: "brown",
                              employmentType: "Plantilla",
                              aligned: true,
                              employeeId: "",
                              image: `https://cdn2.iconfinder.com/data/icons/business-finance-ii-flat/2048/Business_Woman-4096.png`,
                            },
                            children: [
                              {
                                type: "person",
                                expanded: true,
                                data: {
                                  department: "SICU",
                                  deployment: "Emergency",
                                  plantillaItem: "",
                                  prefix: "",
                                  firstName: "Vacant",
                                  middleName: "",
                                  middleInitial: "",
                                  lastName: "",
                                  suffix: "",
                                  postTitle: "",
                                  role: "Vacant",
                                  borderColor: "brown",
                                  employmentType: "Plantilla",
                                  aligned: true,
                                  employeeId: "",
                                  image: `https://cdn2.iconfinder.com/data/icons/business-finance-ii-flat/2048/Business_Woman-4096.png`,
                                },
                                children: [
                                  {
                                    type: "person",
                                    expanded: true,
                                    data: {
                                      department: "PACU",
                                      deployment: "SICU",
                                      plantillaItem: "",
                                      prefix: "",
                                      firstName: "Isabel",
                                      middleName: "",
                                      middleInitial: "",
                                      lastName: "Rivera",
                                      suffix: "",
                                      postTitle: "MD",
                                      role: "Head",
                                      borderColor: "brown",
                                      employmentType: "Plantilla",
                                      aligned: true,
                                      employeeId: "RMBGH-RG-006",
                                      image: `https://cdn2.iconfinder.com/data/icons/business-finance-ii-flat/2048/Business_Woman-4096.png`,
                                    },
                                    children: [],
                                  },
                                ],
                              },
                            ],
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
            ],
          },

          // Ancillary Services - Doc Jocelyn
          {
            type: "person",
            expanded: true,
            data: {
              department: "Ancillary Services",
              deployment: "Assistant Director Office",
              plantillaItem: "",
              prefix: "",
              firstName: "Jocelyn",
              middleName: "",
              middleInitial: "Q",
              lastName: "Gacasan",
              suffix: "",
              postTitle: "MD",
              role: "Assistant Director",
              borderColor: "pink",
              employmentType: "Plantilla",
              aligned: true,
              employeeId: "RMBGH-00005",
              image: `https://cdn2.iconfinder.com/data/icons/business-finance-ii-flat/2048/Business_Woman-4096.png`,
            },
            children: [
              {
                type: "person",
                expanded: true,
                data: {
                  department: "Pathology",
                  deployment: "Ancillary Services",
                  plantillaItem: "",
                  prefix: "",
                  firstName: "Jocelyn",
                  middleName: "",
                  middleInitial: "Q",
                  lastName: "Gacasan",
                  suffix: "",
                  postTitle: "MD",
                  role: "Head",
                  borderColor: "brown",
                  employmentType: "Plantilla",
                  aligned: true,
                  employeeId: "RMBGH-JG-001",
                  image: `https://cdn2.iconfinder.com/data/icons/business-finance-ii-flat/2048/Business_Woman-4096.png`,
                },
                children: [
                  {
                    type: "person",
                    expanded: true,
                    data: {
                      department: "Radiology Department",
                      deployment: "Pathology",
                      plantillaItem: "",
                      prefix: "",
                      firstName: "Maria Angeline ",
                      middleName: "",
                      middleInitial: "DL",
                      lastName: "Nicandro",
                      suffix: "",
                      postTitle: "MD",
                      role: "Head",
                      borderColor: "brown",
                      employmentType: "Plantilla",
                      aligned: true,
                      employeeId: "RMBGH-JG-002",
                      image: `https://cdn2.iconfinder.com/data/icons/business-finance-ii-flat/2048/Business_Woman-4096.png`,
                    },
                    children: [
                      {
                        type: "person",
                        expanded: true,
                        data: {
                          department: "Pharmacy",
                          deployment: "Radiology",
                          plantillaItem: "",
                          prefix: "",
                          firstName: "Maria Victoria",
                          middleName: "",
                          middleInitial: "R",
                          lastName: "Santos",
                          suffix: "",
                          postTitle: "RPH",
                          role: "Head",
                          borderColor: "brown",
                          employmentType: "Plantilla",
                          aligned: true,
                          employeeId: "RMBGH-JG-003",
                          image: `https://cdn2.iconfinder.com/data/icons/business-finance-ii-flat/2048/Business_Woman-4096.png`,
                        },
                        children: [
                          {
                            type: "person",
                            expanded: true,
                            data: {
                              department: "Heart Station",
                              deployment: "Pharmacy",
                              plantillaItem: "",
                              prefix: "",
                              firstName: "Mario Victor",
                              middleName: "M",
                              middleInitial: "M",
                              lastName: "Villardo",
                              suffix: "",
                              postTitle: "MD",
                              role: "Head",
                              borderColor: "brown",
                              employmentType: "Plantilla",
                              aligned: true,
                              employeeId: "RMBGH-JG-004",
                              image: `https://cdn2.iconfinder.com/data/icons/business-finance-ii-flat/2048/Business_Woman-4096.png`,
                            },
                            children: [
                              {
                                type: "person",
                                expanded: true,
                                data: {
                                  department: "Pulmonary Unit",
                                  deployment: "Heart Station",
                                  plantillaItem: "",
                                  prefix: "",
                                  firstName: "Kate Lyn Anne",
                                  middleName: "",
                                  middleInitial: "L",
                                  lastName: "Salvador",
                                  suffix: "",
                                  postTitle: "RRT",
                                  role: "Head",
                                  borderColor: "brown",
                                  employmentType: "Plantilla",
                                  aligned: true,
                                  employeeId: "RMBGH-JG-005",
                                  image: `https://cdn2.iconfinder.com/data/icons/business-finance-ii-flat/2048/Business_Woman-4096.png`,
                                },
                                children: [
                                  {
                                    type: "person",
                                    expanded: true,
                                    data: {
                                      department: "Dental Unit",
                                      deployment: "Pulmonary Unit",
                                      plantillaItem: "",
                                      prefix: "",
                                      firstName: "Arnold Benedict",
                                      middleName: "",
                                      middleInitial: "P",
                                      lastName: "Yambao",
                                      suffix: "",
                                      postTitle: "DMD",
                                      role: "Head",
                                      borderColor: "brown",
                                      employmentType: "Plantilla",
                                      aligned: true,
                                      employeeId: "RMBGH-JG-006",
                                      image: `https://cdn2.iconfinder.com/data/icons/business-finance-ii-flat/2048/Business_Woman-4096.png`,
                                    },
                                    children: [
                                      {
                                        type: "person",
                                        expanded: true,
                                        data: {
                                          department: "Nutrition & Dietetics",
                                          deployment: "Dental Unit",
                                          plantillaItem: "",
                                          prefix: "",
                                          firstName: "Jenifer",
                                          middleName: "C",
                                          middleInitial: "C",
                                          lastName: "Bagon",
                                          suffix: "",
                                          postTitle: "",
                                          role: "Head",
                                          borderColor: "brown",
                                          employmentType: "Plantilla",
                                          aligned: true,
                                          employeeId: "RMBGH-JG-007",
                                          image: `https://cdn2.iconfinder.com/data/icons/business-finance-ii-flat/2048/Business_Woman-4096.png`,
                                        },
                                        children: [],
                                      },
                                    ],
                                  },
                                ],
                              },
                            ],
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },

      // Other Directors remain unchanged
      {
        type: "person",
        expanded: true,
        data: {
          motherUnit: "Hospital Director",
          name: "Raymond Rae R. Castañeda, MD",
          role: "Hospital Director",
          borderColor: "blue",
          employmentType: "Plantilla",
          aligned: true,
          employeeId: "RMBGH-00006",
          image: `https://cdn3.iconfinder.com/data/icons/avatars-flat/33/man_5-1024.png`,
        },
        children: [
          {
            type: "person",
            expanded: true,
            data: {
              department: "Hospital Administration Division",
              deployment: "Administration Unit",
              plantillaItem: "",
              prefix: "",
              firstName: "Bradford",
              middleName: "Antonio",
              middleInitial: "C",
              lastName: "Martinez",
              suffix: "",
              postTitle: "DBA",
              role: "Chief",
              borderColor: "red",
              employmentType: "Plantilla",
              aligned: true,
              employeeId: "RMBGH-00008",
              image:
                "https://cdn3.iconfinder.com/data/icons/avatars-flat/33/man_5-1024.png",
              // Staff under Bradford
              staff: [
                {
                  firstName: "Alice",
                  middleName: "Dela",
                  middleInitial: "D",
                  lastName: "Cruz",
                  suffix: "",
                  postTitle: "",
                  role: "Head Nurse",
                  employmentType: "Plantilla",
                  employeeId: "",
                  image:
                    "https://cdn-icons-png.flaticon.com/512/147/147144.png",
                },
                {
                  firstName: "Brian",
                  middleName: "",
                  middleInitial: "",
                  lastName: "Santos",
                  suffix: "",
                  postTitle: "",
                  role: "Admin Officer",
                  employmentType: "Plantilla",
                  employeeId: "",
                  image:
                    "https://cdn-icons-png.flaticon.com/512/147/147140.png",
                },
                {
                  firstName: "Carla",
                  middleName: "",
                  middleInitial: "",
                  lastName: "Reyes",
                  suffix: "",
                  postTitle: "",
                  role: "HR Staff",
                  employmentType: "Plantilla",
                  employeeId: "",
                  image:
                    "https://cdn-icons-png.flaticon.com/512/147/147132.png",
                },
                {
                  firstName: "Daniel",
                  middleName: "",
                  middleInitial: "",
                  lastName: "Gomez",
                  suffix: "",
                  postTitle: "",
                  role: "Finance Officer",
                  employmentType: "Plantilla",
                  employeeId: "",
                  image:
                    "https://cdn-icons-png.flaticon.com/512/147/147136.png",
                },
                {
                  firstName: "Elena",
                  middleName: "",
                  middleInitial: "",
                  lastName: "Torres",
                  suffix: "",
                  postTitle: "",
                  role: "Quality Officer",
                  employmentType: "Plantilla",
                  employeeId: "",
                  image:
                    "https://cdn-icons-png.flaticon.com/512/147/147140.png",
                },
                {
                  firstName: "Frank",
                  middleName: "",
                  middleInitial: "",
                  lastName: "Medina",
                  suffix: "",
                  postTitle: "",
                  role: "Procurement Officer",
                  employmentType: "Plantilla",
                  employeeId: "",
                  image:
                    "https://cdn-icons-png.flaticon.com/512/147/147133.png",
                },
                {
                  firstName: "Grace",
                  middleName: "",
                  middleInitial: "",
                  lastName: "Villanueva",
                  suffix: "",
                  postTitle: "",
                  role: "Medical Staff",
                  employmentType: "Plantilla",
                  employeeId: "",
                  image:
                    "https://cdn-icons-png.flaticon.com/512/147/147131.png",
                },
                {
                  firstName: "Henry",
                  middleName: "",
                  middleInitial: "",
                  lastName: "Cruz",
                  suffix: "",
                  postTitle: "",
                  role: "Logistics Officer",
                  employmentType: "Plantilla",
                  employeeId: "",
                  image:
                    "https://cdn-icons-png.flaticon.com/512/147/147137.png",
                },
                {
                  firstName: "Isabel",
                  middleName: "",
                  middleInitial: "",
                  lastName: "Lopez",
                  suffix: "",
                  postTitle: "",
                  role: "Nursing Assistant",
                  employmentType: "Plantilla",
                  employeeId: "",
                  image:
                    "https://cdn-icons-png.flaticon.com/512/147/147138.png",
                },
                {
                  firstName: "Jason",
                  middleName: "",
                  middleInitial: "",
                  lastName: "Villanueva",
                  suffix: "",
                  postTitle: "",
                  role: "Admin Staff",
                  employmentType: "Plantilla",
                  employeeId: "",
                  image:
                    "https://cdn-icons-png.flaticon.com/512/147/147139.png",
                },
                {
                  firstName: "Karen",
                  middleName: "",
                  middleInitial: "",
                  lastName: "Santos",
                  suffix: "",
                  postTitle: "",
                  role: "Medical Staff",
                  employmentType: "Plantilla",
                  employeeId: "",
                  image:
                    "https://cdn-icons-png.flaticon.com/512/147/147140.png",
                },
                {
                  firstName: "Luis",
                  middleName: "",
                  middleInitial: "",
                  lastName: "Fernando",
                  suffix: "",
                  postTitle: "",
                  role: "Finance Staff",
                  employmentType: "Plantilla",
                  employeeId: "",
                  image:
                    "https://cdn-icons-png.flaticon.com/512/147/147141.png",
                },
                {
                  firstName: "Maria",
                  middleName: "Dela",
                  middleInitial: "D",
                  lastName: "Cruz",
                  suffix: "",
                  postTitle: "",
                  role: "HR Staff",
                  employmentType: "Plantilla",
                  employeeId: "",
                  image:
                    "https://cdn-icons-png.flaticon.com/512/147/147142.png",
                },
                {
                  firstName: "Nico",
                  middleName: "",
                  middleInitial: "",
                  lastName: "Reyes",
                  suffix: "",
                  postTitle: "",
                  role: "Logistics Staff",
                  employmentType: "Plantilla",
                  employeeId: "",
                  image:
                    "https://cdn-icons-png.flaticon.com/512/147/147143.png",
                },
                {
                  firstName: "Olivia",
                  middleName: "",
                  middleInitial: "",
                  lastName: "Torres",
                  suffix: "",
                  postTitle: "",
                  role: "Nursing Staff",
                  employmentType: "Plantilla",
                  employeeId: "",
                  image:
                    "https://cdn-icons-png.flaticon.com/512/147/147144.png",
                },
                {
                  firstName: "Patrick",
                  middleName: "",
                  middleInitial: "",
                  lastName: "Gomez",
                  suffix: "",
                  postTitle: "",
                  role: "Medical Assistant",
                  employmentType: "Plantilla",
                  employeeId: "",
                  image:
                    "https://cdn-icons-png.flaticon.com/512/147/147145.png",
                },
                {
                  firstName: "Quincy",
                  middleName: "",
                  middleInitial: "",
                  lastName: "Medina",
                  suffix: "",
                  postTitle: "",
                  role: "Support Staff",
                  employmentType: "Plantilla",
                  employeeId: "",
                  image:
                    "https://cdn-icons-png.flaticon.com/512/147/147146.png",
                },
                {
                  firstName: "Vacant",
                  middleName: "",
                  middleInitial: "",
                  lastName: "",
                  suffix: "",
                  postTitle: "",
                  role: "Legal",
                  employmentType: "Vacant",
                  employeeId: "",
                  image:
                    "https://cdn-icons-png.flaticon.com/512/147/147147.png",
                },
              ],
            },
            children: [
              {
                type: "person",
                expanded: true,
                data: {
                  motherUnit: "Facility Management Division",
                  name: "Engr. Marc Napoleon A. Quiaoit III",
                  role: "Chief",
                  borderColor: "purple",
                  employmentType: "Plantilla",
                  aligned: true,
                  employeeId: "RMBGH-00007",
                  image: `https://cdn3.iconfinder.com/data/icons/avatars-flat/33/man_5-1024.png`,
                },
                children: [
                  {
                    type: "person",
                    expanded: true,
                    data: {
                      motherUnit: "Property Management",
                      name: "Engr. Joshua Anthony L. Palaad",
                      role: "Head",
                      borderColor: "brown",
                      employmentType: "Plantilla",
                      employeeId: "RMBGH-FM-001",
                      image: `https://cdn3.iconfinder.com/data/icons/avatars-flat/33/man_5-1024.png`,
                    },
                    children: [
                      {
                        type: "person",
                        expanded: true,
                        data: {
                          motherUnit: "Engineering Department",
                          name: "Engr. Cristopher P. Española",
                          role: "Officer-In-Charge",
                          borderColor: "brown",
                          employmentType: "Plantilla",
                          employeeId: "RMBGH-FM-002",
                          image: `https://cdn3.iconfinder.com/data/icons/avatars-flat/33/man_5-1024.png`,
                        },
                        children: [
                          {
                            type: "person",
                            expanded: true,
                            data: {
                              motherUnit: "Design and Planning",
                              name: "Engr. Marc Napoleon A. Quiaoit III",
                              role: "Head",
                              borderColor: "brown",
                              employmentType: "Plantilla",
                              employeeId: "RMBGH-FM-003",
                              image: `https://cdn2.iconfinder.com/data/icons/business-finance-ii-flat/2048/Business_Woman-4096.png`,
                            },
                            children: [
                              {
                                type: "person",
                                expanded: true,
                                data: {
                                  motherUnit: "Linen/Housekeeping",
                                  name: "Cherry N. Borja",
                                  role: "Officer-In-Charge",
                                  borderColor: "brown",
                                  employmentType: "Plantilla",
                                  employeeId: "RMBGH-FM-004",
                                  image: `https://cdn3.iconfinder.com/data/icons/avatars-flat/33/man_5-1024.png`,
                                },
                                children: [
                                  {
                                    type: "person",
                                    expanded: true,
                                    data: {
                                      motherUnit: "Security",
                                      name: "Apolinario R. Autor",
                                      role: "Officer-In-Charge",
                                      borderColor: "brown",
                                      employmentType: "Plantilla",
                                      employeeId: "RMBGH-FM-005",
                                      image: `https://cdn2.iconfinder.com/data/icons/business-finance-ii-flat/2048/Business_Woman-4096.png`,
                                    },
                                    children: [],
                                  },
                                ],
                              },
                            ],
                          },
                        ],
                      },
                    ],
                  },
                ],
              },

              // Ruel subtree as sibling
              {
                type: "person",
                expanded: true,
                data: {
                  motherUnit: "Health Information Management Cluster",
                  name: "Ruel V. Subaran",
                  role: "Officer-In-Charge",
                  borderColor: "purple",
                  employmentType: "Plantilla",
                  aligned: true,
                  employeeId: "RMBGH-00009",
                  image:
                    "https://cdn3.iconfinder.com/data/icons/avatars-flat/33/man_5-1024.png",
                  // Added staff members
                  staff: [
                    {
                      name: "Ma. Lourdes Teresa E. Jawili",
                      role: "Head",
                      employeeId: "RMBGH-HIM-STAFF-001",
                      employmentType: "Plantilla",
                      image:
                        "https://cdn3.iconfinder.com/data/icons/avatars-flat/33/man_5-1024.png",
                    },
                    {
                      name: "John Bert I. Doqurenia",
                      role: "Officer-In-Charge",
                      employeeId: "RMBGH-HIM-STAFF-001",
                      employmentType: "Plantilla",
                      image:
                        "https://cdn3.iconfinder.com/data/icons/avatars-flat/33/man_5-1024.png",
                    },
                    {
                      name: "Julina N. De Asis",
                      role: "Officer-In-Charge",
                      employeeId: "RMBGH-HIM-STAFF-001",
                      employmentType: "Plantilla",
                      image:
                        "https://cdn3.iconfinder.com/data/icons/avatars-flat/33/man_5-1024.png",
                    },
                  ],
                },
                children: [
                  {
                    type: "person",
                    expanded: true,
                    data: {
                      motherUnit: "Medical Records",
                      name: "Ma. Lourdes Teresa E. Jawili",
                      role: "Head",
                      borderColor: "brown",
                      employmentType: "Plantilla",
                      employeeId: "RMBGH-HIM-001",
                      image:
                        "https://cdn2.iconfinder.com/data/icons/business-finance-ii-flat/2048/Business_Woman-4096.png",
                    },
                    children: [
                      {
                        type: "person",
                        expanded: true,
                        data: {
                          department: "Information Technology",
                          deployment: "IT Unit",
                          plantillaItem: "",
                          prefix: "",
                          firstName: "Jan Bert",
                          middleName: "I.",
                          middleInitial: "I",
                          lastName: "Doquenia",
                          suffix: "",
                          postTitle: "",
                          role: "Officer-In-Charge",
                          borderColor: "brown",
                          employmentType: "Plantilla",
                          aligned: true,
                          employeeId: "RMBGH-HIM-002",
                          image:
                            "https://cdn3.iconfinder.com/data/icons/avatars-flat/33/man_5-1024.png",
                          staff: [
                            {
                              firstName: "John Benedict",
                              middleName: "O.",
                              middleInitial: "O",
                              lastName: "Fernando",
                              suffix: "",
                              postTitle: "",
                              role: "Data Controller",
                              employmentType: "Plantilla",
                              employeeId: "RMBGH-HIM-STAFF-001",
                              image:
                                "https://cdn3.iconfinder.com/data/icons/avatars-flat/33/man_5-1024.png",
                            },
                            {
                              firstName: "Michael Benedict",
                              middleName: "T.",
                              middleInitial: "T",
                              lastName: "Villamor",
                              suffix: "",
                              postTitle: "",
                              role: "Data Controller",
                              employmentType: "Plantilla",
                              employeeId: "RMBGH-HIM-STAFF-002",
                              image:
                                "https://cdn3.iconfinder.com/data/icons/avatars-flat/33/man_5-1024.png",
                            },
                            {
                              firstName: "Edison",
                              middleName: "R.",
                              middleInitial: "R",
                              lastName: "Campo Jr.",
                              suffix: "",
                              postTitle: "",
                              role: "Data Controller",
                              employmentType: "Contract of Service",
                              employeeId: "RMBGH-HIM-STAFF-003",
                              image:
                                "https://cdn3.iconfinder.com/data/icons/avatars-flat/33/man_5-1024.png",
                            },
                            {
                              firstName: "Sharmaine",
                              middleName: "D.",
                              middleInitial: "D",
                              lastName: "Banquiles",
                              suffix: "",
                              postTitle: "",
                              role: "Data Controller",
                              employmentType: "Contract of Service",
                              employeeId: "RMBGH-HIM-STAFF-004",
                              image:
                                "https://cdn3.iconfinder.com/data/icons/avatars-flat/33/man_5-1024.png",
                            },
                            {
                              firstName: "Colin",
                              middleName: "B.",
                              middleInitial: "B",
                              lastName: "Arias",
                              suffix: "",
                              postTitle: "",
                              role: "Data Controller",
                              employmentType: "Contract of Service",
                              employeeId: "RMBGH-HIM-STAFF-005",
                              image:
                                "https://cdn3.iconfinder.com/data/icons/avatars-flat/33/man_5-1024.png",
                            },
                            {
                              firstName: "John Carlo",
                              middleName: "V.",
                              middleInitial: "V",
                              lastName: "Goco",
                              suffix: "",
                              postTitle: "",
                              role: "Data Controller",
                              employmentType: "Contract of Service",
                              employeeId: "RMBGH-HIM-STAFF-006",
                              image:
                                "https://cdn3.iconfinder.com/data/icons/avatars-flat/33/man_5-1024.png",
                            },
                          ],
                        },
                        children: [
                          {
                            type: "person",
                            expanded: true,
                            data: {
                              department: "Admitting Section",
                              deployment: "Admitting Section Unit",
                              plantillaItem: "",
                              prefix: "",
                              firstName: "Julina",
                              middleName: "N.",
                              middleInitial: "N",
                              lastName: "De Asis",
                              suffix: "",
                              postTitle: "",
                              role: "Officer-In-Charge",
                              borderColor: "brown",
                              employmentType: "Plantilla",
                              aligned: true,
                              employeeId: "RMBGH-HIM-003",
                              image:
                                "https://cdn3.iconfinder.com/data/icons/avatars-flat/33/man_5-1024.png",
                            },
                            children: [],
                          },
                        ],
                      },
                    ],
                  },
                ],
              },

              // Moved Cristela here to align horizontally with Joshua, Lourdes, Cristina
              {
                type: "person",
                expanded: true,
                data: {
                  motherUnit: "Administrative Services Cluster",
                  name: "Cristela V. Veñegas, MD",
                  role: "Head",
                  borderColor: "brown",
                  employmentType: "Plantilla",
                  aligned: true,
                  employeeId: "RMBGH-00010",
                  image:
                    "https://cdn3.iconfinder.com/data/icons/avatars-flat/33/man_5-1024.png",
                },
                children: [
                  {
                    type: "person",
                    expanded: true,
                    data: {
                      department: "Human Resources",
                      deployment: "Human Resources Office",
                      plantillaItem: "",
                      prefix: "",
                      firstName: "Naomi Noreen",
                      middleName: "O.",
                      middleInitial: "O",
                      lastName: "Buenafe",
                      suffix: "",
                      postTitle: "",
                      role: "Officer-In-Charge",
                      borderColor: "brown",
                      employmentType: "Plantilla",
                      aligned: true,
                      employeeId: "RMBGH-00010",
                      image:
                        "https://cdn3.iconfinder.com/data/icons/avatars-flat/33/man_5-1024.png",

                      staff: [
                        {
                          department: "Human Resources",
                          deployment: "Human Resources Office",
                          plantillaItem: "",
                          prefix: "",
                          firstName: "Vanessa Mae",
                          middleName: "",
                          middleInitial: "",
                          lastName: "Estidola",
                          suffix: "",
                          postTitle: "",
                          role: "",
                          borderColor: "black",
                          employmentType: "Plantilla",
                          employeeId: "RMBGH-00010",
                          image:
                            "https://cdn-icons-png.flaticon.com/512/147/147144.png",
                        },
                        {
                          department: "Human Resources",
                          deployment: "Human Resources Office",
                          plantillaItem: "",
                          prefix: "",
                          firstName: "Christine Joy",
                          middleName: "",
                          middleInitial: "",
                          lastName: "Tango",
                          suffix: "",
                          postTitle: "",
                          role: "",
                          borderColor: "black",
                          employmentType: "Plantilla",
                          employeeId: "RMBGH-00010",
                          image:
                            "https://cdn-icons-png.flaticon.com/512/147/147144.png",
                        },
                        {
                          department: "Human Resources",
                          deployment: "Human Resources Office",
                          plantillaItem: "",
                          prefix: "",
                          firstName: "Marie Joy",
                          middleName: "",
                          middleInitial: "",
                          lastName: "Sillon",
                          suffix: "",
                          postTitle: "",
                          role: "",
                          borderColor: "black",
                          employmentType: "Plantilla",
                          employeeId: "RMBGH-00010",
                          image:
                            "https://cdn-icons-png.flaticon.com/512/147/147144.png",
                        },
                        {
                          department: "Human Resources",
                          deployment: "Human Resources Office",
                          plantillaItem: "",
                          prefix: "",
                          firstName: "Carmen",
                          middleName: "",
                          middleInitial: "",
                          lastName: "Cellonia",
                          suffix: "",
                          postTitle: "",
                          role: "",
                          borderColor: "black",
                          employmentType: "Plantilla",
                          employeeId: "RMBGH-00010",
                          image:
                            "https://cdn-icons-png.flaticon.com/512/147/147144.png",
                        },
                        {
                          department: "Human Resources",
                          deployment: "Human Resources Office",
                          plantillaItem: "",
                          prefix: "",
                          firstName: "Cristina",
                          middleName: "",
                          middleInitial: "",
                          lastName: "Arzanan",
                          suffix: "",
                          postTitle: "",
                          role: "",
                          borderColor: "black",
                          employmentType: "Plantilla",
                          employeeId: "RMBGH-00010",
                          image:
                            "https://cdn-icons-png.flaticon.com/512/147/147144.png",
                        },
                        {
                          department: "Human Resources",
                          deployment: "Human Resources Office",
                          plantillaItem: "",
                          prefix: "",
                          firstName: "Clilene",
                          middleName: "",
                          middleInitial: "",
                          lastName: "Perez",
                          suffix: "",
                          postTitle: "",
                          role: "",
                          borderColor: "black",
                          employmentType: "Plantilla",
                          employeeId: "RMBGH-00010",
                          image:
                            "https://cdn-icons-png.flaticon.com/512/147/147144.png",
                        },
                        {
                          department: "Human Resources",
                          deployment: "Human Resources Office",
                          plantillaItem: "",
                          prefix: "",
                          firstName: "Jessa",
                          middleName: "",
                          middleInitial: "",
                          lastName: "Faustino",
                          suffix: "",
                          postTitle: "",
                          role: "",
                          borderColor: "black",
                          employmentType: "Plantilla",
                          employeeId: "RMBGH-00010",
                          image:
                            "https://cdn-icons-png.flaticon.com/512/147/147144.png",
                        },
                        {
                          department: "Human Resources",
                          deployment: "Human Resources Office",
                          plantillaItem: "",
                          prefix: "",
                          firstName: "Renz",
                          middleName: "",
                          middleInitial: "",
                          lastName: "Pascual",
                          suffix: "",
                          postTitle: "",
                          role: "",
                          borderColor: "black",
                          employmentType: "Plantilla",
                          employeeId: "RMBGH-00010",
                          image:
                            "https://cdn-icons-png.flaticon.com/512/147/147144.png",
                        },
                        {
                          department: "Human Resources",
                          deployment: "Human Resources Office",
                          plantillaItem: "",
                          prefix: "",
                          firstName: "Mary Joy",
                          middleName: "",
                          middleInitial: "",
                          lastName: "Dizon",
                          suffix: "",
                          postTitle: "",
                          role: "",
                          borderColor: "black",
                          employmentType: "Plantilla",
                          employeeId: "RMBGH-00010",
                          image:
                            "https://cdn-icons-png.flaticon.com/512/147/147144.png",
                        },
                        {
                          department: "Human Resources",
                          deployment: "Human Resources Office",
                          plantillaItem: "",
                          prefix: "",
                          firstName: "Administrative Aide III",
                          middleName: "",
                          middleInitial: "",
                          lastName: "",
                          suffix: "",
                          postTitle: "",
                          role: "",
                          borderColor: "black",
                          employmentType: "Vices",
                          employeeId: "RMBGH-00010",
                          image:
                            "https://cdn-icons-png.flaticon.com/512/147/147144.png",
                        },
                        {
                          department: "Human Resources",
                          deployment: "Human Resources Office",
                          plantillaItem: "",
                          prefix: "",
                          firstName: "Mark",
                          middleName: "",
                          middleInitial: "",
                          lastName: "",
                          suffix: "",
                          postTitle: "",
                          role: "",
                          borderColor: "black",
                          employmentType: "Contract of Service",
                          employeeId: "RMBGH-00010",
                          image:
                            "https://cdn-icons-png.flaticon.com/512/147/147144.png",
                        },
                      ],
                    },

                    children: [
                      {
                        type: "person",
                        expanded: true,
                        data: {
                          motherUnit: "Vacant",
                          name: "Vacant",
                          role: "Vacant",
                          borderColor: "brown",
                          employmentType: "Plantilla",
                          aligned: true,
                          employeeId: "RMBGH-00010",
                          image:
                            "https://cdn3.iconfinder.com/data/icons/avatars-flat/33/man_5-1024.png",
                        },
                        children: [
                          {
                            type: "person",
                            expanded: true,
                            data: {
                              motherUnit: "Data Protection",
                              name: "Cristela V. Veñegas, MD",
                              role: "Officer",
                              borderColor: "brown",
                              employmentType: "Plantilla",
                              aligned: true,
                              employeeId: "RMBGH-00010",
                              image:
                                "https://cdn3.iconfinder.com/data/icons/avatars-flat/33/man_5-1024.png",
                            },
                            children: [
                              {
                                type: "person",
                                expanded: true,
                                data: {
                                  motherUnit: "Customer Relations Management",
                                  name: "Sharon Grace V. Meneses, MD",
                                  role: "Head",
                                  borderColor: "brown",
                                  employmentType: "Plantilla",
                                  aligned: true,
                                  employeeId: "RMBGH-00010",
                                  image:
                                    "https://cdn3.iconfinder.com/data/icons/avatars-flat/33/man_5-1024.png",
                                },
                                children: [],
                              },
                            ],
                          },
                        ],
                      },
                    ],
                  },
                ],
              },

              // Uziel subtree stays as sibling as well
              {
                type: "person",
                expanded: true,
                data: {
                  motherUnit: "Patient Care Support Services Cluster",
                  name: "Uziel A. Rutaquio, RSW",
                  role: "Head",
                  borderColor: "purple",
                  employmentType: "Plantilla",
                  aligned: true,
                  employeeId: "RMBGH-00010",
                  image:
                    "https://cdn3.iconfinder.com/data/icons/avatars-flat/33/man_5-1024.png",
                },
                children: [
                  {
                    type: "person",
                    expanded: true,
                    data: {
                      motherUnit: "Medical Social Service Department",
                      name: "Ma. Cristina D. Pacubas, RSW",
                      role: "Officer-In-Charge",
                      borderColor: "brown",
                      employmentType: "Plantilla",
                      employeeId: "RMBGH-MSS-001",
                      image:
                        "https://cdn2.iconfinder.com/data/icons/business-finance-ii-flat/2048/Business_Woman-4096.png",
                    },
                    children: [
                      {
                        type: "person",
                        expanded: true,
                        data: {
                          motherUnit: "Medical Social Service Department",
                          name: "Vacant",
                          role: "Staff",
                          borderColor: "brown",
                          employmentType: "Plantilla",
                          employeeId: "RMBGH-MSS-002",
                          image:
                            "https://cdn3.iconfinder.com/data/icons/avatars-flat/33/man_5-1024.png",
                        },
                        children: [],
                      },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },

      {
        type: "person",
        expanded: true,
        data: {
          motherUnit: "Finance Director",
          name: "Pia Angelina C. Tan, CPA",
          role: "Finance Director",
          borderColor: "blue",
          employmentType: "Plantilla",
          aligned: true,
          employeeId: "RMBGH-00011",
          image:
            "https://cdn2.iconfinder.com/data/icons/business-finance-ii-flat/2048/Business_Woman-4096.png",
          staff: [
            // Secretary under Pia for modal
            {
              name: "Secretary 1",
              role: "Secretary",
              employeeId: "RMBGH-SEC-FIN-001",
              image:
                "https://cdn3.iconfinder.com/data/icons/avatars-flat/33/man_5-1024.png",
            },
          ],
        },
        children: [
          // Finance Services subtree
          {
            type: "person",
            expanded: true,
            data: {
              motherUnit: "Finance Services",
              name: "Ronilo M. Jose, CPA",
              role: "Head",
              borderColor: "brown",
              employmentType: "Plantilla",
              aligned: true,
              employeeId: "RMBGH-FIN-CL-001",
              image:
                "https://cdn3.iconfinder.com/data/icons/avatars-flat/33/man_5-1024.png",
            },
            children: [
              {
                type: "person",
                expanded: true,
                data: {
                  motherUnit: "Budget Department",
                  name: "Maria Ruth S. Galut",
                  role: "Officer-In-Charge",
                  borderColor: "brown",
                  employmentType: "Plantilla",
                  aligned: true,
                  employeeId: "RMBGH-FIN-001",
                  image:
                    "https://cdn2.iconfinder.com/data/icons/business-finance-ii-flat/2048/Business_Woman-4096.png",
                },
                children: [
                  {
                    type: "person",
                    expanded: true,
                    data: {
                      motherUnit: "Billing and Claims",
                      name: "Judith Fatima E. Garcia, MD",
                      role: "Head",
                      borderColor: "brown",
                      employmentType: "Plantilla",
                      aligned: true,
                      employeeId: "RMBGH-FIN-002",
                      image:
                        "https://cdn2.iconfinder.com/data/icons/business-finance-ii-flat/2048/Business_Woman-4096.png",
                    },
                    children: [
                      {
                        type: "person",
                        expanded: true,
                        data: {
                          motherUnit: "Procurement/Warehouse/Inventory",
                          name: "Donnary Gavan",
                          role: "",
                          borderColor: "brown",
                          employmentType: "Plantilla",
                          aligned: true,
                          employeeId: "RMBGH-FIN-003",
                          image:
                            "https://cdn3.iconfinder.com/data/icons/avatars-flat/33/man_5-1024.png",
                        },
                        children: [
                          {
                            type: "person",
                            expanded: true,
                            data: {
                              motherUnit: "Cash Management",
                              name: "Marion May M. Cervera",
                              role: "Head",
                              borderColor: "brown",
                              employmentType: "Plantilla",
                              aligned: true,
                              employeeId: "RMBGH-FIN-004",
                              image:
                                "https://cdn3.iconfinder.com/data/icons/avatars-flat/33/man_5-1024.png",
                            },
                            children: [],
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },

      {
        type: "person",
        expanded: true,
        data: {
          motherUnit: "Nursing Director",
          name: "Neil G. Cabbo, RN, MAN",
          role: "Nursing Director",
          borderColor: "blue",
          employmentType: "Plantilla",
          aligned: true,
          employeeId: "RMBGH-00012",
          image: `https://cdn3.iconfinder.com/data/icons/avatars-flat/33/man_5-1024.png`,
        },
        children: [
          // LEFT ASSISTANT
          {
            type: "person",
            expanded: true,
            data: {
              motherUnit: "Assistant Nursing Director",
              name: "Ma. Vicarl T. Estacio, RN",
              role: "for Patient Services / Division Secretary",
              borderColor: "purple",
              employmentType: "Plantilla",
              aligned: true,
              employeeId: "RMBGH-NUR-001",
              image: `https://cdn2.iconfinder.com/data/icons/business-finance-ii-flat/2048/Business_Woman-4096.png`,
            },
            children: [
              {
                type: "person",
                expanded: true,
                data: {
                  motherUnit: "Infection Prevention & Control Nurse",
                  name: "Ma. Vicarl T. Estacio, RN",
                  role: "IPCN",
                  borderColor: "brown",
                  employmentType: "Plantilla",
                  employeeId: "RMBGH-NUR-002",
                  image: `https://cdn2.iconfinder.com/data/icons/business-finance-ii-flat/2048/Business_Woman-4096.png`,
                },
                children: [
                  {
                    type: "person",
                    expanded: true,
                    data: {
                      motherUnit: "Nursing Quality & Assurance Nurse",
                      name: "Kimberly Beth P. Kampton, RN",
                      role: "NQAN",
                      borderColor: "brown",
                      employmentType: "Plantilla",
                      employeeId: "RMBGH-NUR-003",
                      image: `https://cdn2.iconfinder.com/data/icons/business-finance-ii-flat/2048/Business_Woman-4096.png`,
                    },
                    children: [],
                  },
                ],
              },
            ],
          },

          // CENTER SUPERVISORS (VERTICAL)
          {
            type: "person",
            expanded: true,
            data: {
              motherUnit: "Outpatient Department",
              name: "Marijane A. Lagno, RN",
              role: "Supervisor",
              borderColor: "brown",
              employmentType: "Plantilla",
              employeeId: "RMBGH-NUR-004",
              image: `https://cdn2.iconfinder.com/data/icons/business-finance-ii-flat/2048/Business_Woman-4096.png`,
            },
            children: [
              {
                type: "person",
                expanded: true,
                data: {
                  motherUnit: "Emergency Room",
                  name: "Connie Ann H. Silva, RN",
                  role: "Supervisor",
                  borderColor: "brown",
                  employmentType: "Plantilla",
                  employeeId: "RMBGH-NUR-005",
                  image: `https://cdn2.iconfinder.com/data/icons/business-finance-ii-flat/2048/Business_Woman-4096.png`,
                },
                children: [
                  {
                    type: "person",
                    expanded: true,
                    data: {
                      motherUnit: "OR / DR",
                      name: "Herminio E. Sarmiento, RN",
                      role: "Supervisor",
                      borderColor: "brown",
                      employmentType: "Plantilla",
                      employeeId: "RMBGH-NUR-006",
                      image: `https://cdn3.iconfinder.com/data/icons/avatars-flat/33/man_5-1024.png`,
                    },
                    children: [
                      {
                        type: "person",
                        expanded: true,
                        data: {
                          motherUnit: "Special Care Department",
                          name: "Noreen Eunice C. Cruz, RN",
                          role: "Supervisor",
                          borderColor: "brown",
                          employmentType: "Plantilla",
                          employeeId: "RMBGH-NUR-007",
                          image: `https://cdn2.iconfinder.com/data/icons/business-finance-ii-flat/2048/Business_Woman-4096.png`,
                        },
                        children: [
                          {
                            type: "person",
                            expanded: true,
                            data: {
                              motherUnit: "General Nursing Department",
                              name: "Ranee G. Sangalang, RM, RN, MAN",
                              role: "Supervisor",
                              borderColor: "brown",
                              employmentType: "Plantilla",
                              employeeId: "RMBGH-NUR-008",
                              image: `https://cdn2.iconfinder.com/data/icons/business-finance-ii-flat/2048/Business_Woman-4096.png`,
                            },
                            children: [
                              {
                                type: "person",
                                expanded: true,
                                data: {
                                  motherUnit:
                                    "Central Supply & Sterilization Department",
                                  name: "Darwin O. Leonardo, RN",
                                  role: "Supervisor",
                                  borderColor: "brown",
                                  employmentType: "Plantilla",
                                  employeeId: "RMBGH-NUR-009",
                                  image: `https://cdn3.iconfinder.com/data/icons/avatars-flat/33/man_5-1024.png`,
                                },
                                children: [],
                              },
                            ],
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
            ],
          },

          // RIGHT ASSISTANT
          {
            type: "person",
            expanded: true,
            data: {
              motherUnit: "Assistant Nursing Director",
              name: "Lady Jane G. Gaffud-Carabagan, RN, MAN",
              role: "for Administration & Training",
              borderColor: "purple",
              employmentType: "Plantilla",
              aligned: true,
              employeeId: "RMBGH-NUR-010",
              image: `https://cdn2.iconfinder.com/data/icons/business-finance-ii-flat/2048/Business_Woman-4096.png`,
            },
            children: [
              {
                type: "person",
                expanded: true,
                data: {
                  motherUnit: "Research",
                  name: "Vacant",
                  role: "Vacant",
                  borderColor: "gray",
                  employmentType: "Plantilla",
                  employeeId: "",
                  image: `https://cdn3.iconfinder.com/data/icons/avatars-flat/33/man_5-1024.png`,
                },
                children: [
                  {
                    type: "person",
                    expanded: true,
                    data: {
                      motherUnit: "Community Extension",
                      name: "Vacant",
                      role: "Vacant",
                      borderColor: "gray",
                      employmentType: "Plantilla",
                      employeeId: "",
                      image: `https://cdn3.iconfinder.com/data/icons/avatars-flat/33/man_5-1024.png`,
                    },
                    children: [],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
];
