export const forwardedMails = [
  {
    id: 1,
    title: "Patient Safety Week Advisory",
    originalSender: "Administration",
    forwardedTo: "IT",
    forwardedToLabel: "Information Technology",
    date: "Jun 6, 2025",
    time: "10:15 AM",
    status: "delivered",
    note: "Please take note of this advisory for the upcoming safety week.",
    content: "This is to inform all employees that Patient Safety Week will be celebrated from May 27 to May 31, 2024.\n\nPlease see attached memorandum for the complete schedule.\n\nThank you.",
    attachment: "Patient_Safety_Week_Memo.pdf",
  },
  {
    id: 2,
    title: "Fire Drill Schedule",
    originalSender: "Safety Office",
    forwardedTo: "all",
    forwardedToLabel: "All Employees",
    date: "Jun 2, 2025",
    time: "3:00 PM",
    status: "delivered",
    note: "",
    content: "A mandatory fire drill will be conducted on May 24, 2024 at 3:00 PM.",
    attachment: null,
  },
  {
    id: 3,
    title: "Holiday Announcement",
    originalSender: "Administration",
    forwardedTo: "IT",
    forwardedToLabel: "Information Technology",
    date: "May 28, 2025",
    time: "8:00 AM",
    status: "delivered",
    note: "FYI for the team.",
    content: "The hospital will be observing the upcoming national holiday on May 27, 2024.",
    attachment: null,
  },
  {
    id: 4,
    title: "IT Announcement",
    originalSender: "Administration",
    forwardedTo: "IT",
    forwardedToLabel: "Information Technology",
    date: "March 28, 2025",
    time: "8:00 AM",
    status: "delivered",
    note: "FYI for the team.",
    content: "Lorem ipsum",
    attachment: "IT_Memo.doc",
  },
];