export const sentMails = [
  {
    id: 1,
    title: "IT Security Reminder",
    recipients: "IT",
    recipientLabel: "Information Technology",
    date: "Jun 5, 2025",
    time: "9:00 AM",
    status: "delivered",
    emailType: "advisory",
    emailTypeLabel: "Advisory",
    content: "Please be reminded to change your passwords every 30 days and avoid sharing credentials with anyone.\n\nThis is part of our ongoing effort to maintain IT security across the hospital.",
    attachment: null,
  },
  {
    id: 2,
    title: "Team Sync Meeting",
    recipients: "IT",
    recipientLabel: "Information Technology",
    date: "Jun 3, 2025",
    time: "2:00 PM",
    status: "delivered",
    emailType: "notice",
    emailTypeLabel: "Notice",
    content: "We will be having a team sync this Friday at 3:00 PM via the conference room. Please make sure to attend.",
    attachment: null,
  },
  {
    id: 3,
    title: "System Downtime Notice",
    recipients: "all",
    recipientLabel: "All Employees",
    date: "May 30, 2025",
    time: "11:30 AM",
    status: "delivered",
    emailType: "memorandum",
    emailTypeLabel: "Memorandum",
    content: "The hospital management system will be down for maintenance on June 1, 2025 from 12:00 AM to 4:00 AM.",
    attachment: "Maintenance_Schedule.pdf",
  },
  {
    id: 4,
    title: "New Software Deployment",
    recipients: "IT",
    recipientLabel: "Information Technology",
    date: "May 25, 2025",
    time: "8:45 AM",
    status: "pending",
    emailType: "circular",
    emailTypeLabel: "Circular",
    content: "A new version of the hospital records system will be deployed next week. Training sessions will be scheduled accordingly.",
    attachment: null,
  },
];