// recipient: "all" = all employees | departmentId (e.g. "IT") = dept only
export const announcements = [
  {
    id: 1,
    title: "Patient Safety Week Advisory",
    sender: "Administration",
    senderDeptId: "ADMIN",
    recipient: "all",
    priority: "urgent",
    unread: true,
    date: "May 21, 2024",
    time: "9:30 AM",
    attachment: "Patient_Safety_Week_Memo.pdf",
    content:
      "This is to inform all employees that Patient Safety Week will be celebrated from May 27 to May 31, 2024.\n\nPlease see attached memorandum for the complete schedule.\n\nThank you.",
  },
  {
    id: 2,
    title: "Laboratory Equipment Maintenance",
    sender: "Laboratory Department",
    senderDeptId: "LAB",
    recipient: "LAB",
    priority: "important",
    unread: true,
    date: "May 20, 2024",
    time: "8:15 AM",
    content: "Scheduled maintenance for all laboratory equipment this Friday.",
  },
  {
    id: 3,
    title: "HR Policy Update",
    sender: "Human Resources",
    senderDeptId: "HR",
    recipient: "HR",
    priority: "normal",
    unread: false,
    date: "May 19, 2024",
    time: "1:00 PM",
    content: "Updated attendance and leave policy effective immediately.",
  },
  {
    id: 4,
    title: "IT System Maintenance Notice",
    sender: "IT Department",
    senderDeptId: "IT",
    recipient: "IT",
    priority: "important",
    unread: true,
    date: "May 18, 2024",
    time: "10:00 AM",
    content: "System maintenance scheduled this Saturday from 12:00 AM to 4:00 AM. Please save all work beforehand.",
  },
  {
    id: 5,
    title: "Fire Drill Schedule",
    sender: "Safety Office",
    senderDeptId: "ADMIN",
    recipient: "all",
    priority: "urgent",
    unread: true,
    date: "May 17, 2024",
    time: "2:30 PM",
    content: "A mandatory fire drill will be conducted on May 24, 2024 at 3:00 PM.",
  },
  {
    id: 6,
    title: "Holiday Announcement",
    sender: "Administration",
    senderDeptId: "ADMIN",
    recipient: "all",
    priority: "normal",
    unread: false,
    date: "May 16, 2024",
    time: "9:00 AM",
    content: "The hospital will be observing the upcoming national holiday on May 27, 2024.",
  },
];